// Single source of truth for the 4-layer reliability system.
// Order matters — used by demo timeline, scroll story, and system loop.
export const SYSTEM_LAYERS = [
  {
    id: "predict",
    action: "Predict",
    system: "PRISM",
    href: "/cases/prism",
    eyebrow: "Predict · Service Intelligence",
    headline: "Failures are rarely sudden.",
    body: "They build silently across systems, distributed across time — before, during, and after every visit.",
    accent: "indigo",
    hex: "#6366F1",
    dot: "bg-indigo-400",
    border: "border-indigo-400/30",
    bg: "bg-indigo-400/10",
    text: "text-indigo-300",
  },
  {
    id: "prevent",
    action: "Prevent",
    system: "CliniGuard",
    href: "/cases/cliniguard",
    liveHref: "/cliniguard",
    eyebrow: "Prevent · System Health",
    headline: "What if systems detected risk before failure?",
    body: "Continuous health intelligence that surfaces invisible degradation between procedures, before it ever reaches a patient.",
    accent: "emerald",
    hex: "#22C55E",
    dot: "bg-emerald-400",
    border: "border-emerald-400/30",
    bg: "bg-emerald-400/10",
    text: "text-emerald-300",
  },
  {
    id: "assist",
    action: "Assist",
    system: "HoloGuide",
    href: "/cases/hologuide",
    liveHref: "/holiguide",
    eyebrow: "Assist · AR Field Repair",
    headline: "When failures happen, resolution must be immediate.",
    body: "Real-time AR guidance gives field engineers spatial context exactly when and where they need it.",
    accent: "blue",
    hex: "#3B82F6",
    dot: "bg-blue-400",
    border: "border-blue-400/30",
    bg: "bg-blue-400/10",
    text: "text-blue-300",
  },
  {
    id: "recover",
    action: "Recover",
    system: "ARIS",
    href: "/cases/aris",
    eyebrow: "Recover · Rollback Intelligence",
    headline: "Recovery must be safe, fast, and consistent.",
    body: "Automated rollback intelligence makes the right recovery decision — and learns from every outcome.",
    accent: "violet",
    hex: "#A78BFA",
    dot: "bg-violet-400",
    border: "border-violet-400/30",
    bg: "bg-violet-400/10",
    text: "text-violet-300",
  },
];

export const STORY_BEATS = [
  {
    id: "hero",
    text: "Healthcare systems fail in two ways — when something breaks, and when no one sees it coming.",
    duration: 3500,
  },
  {
    id: "system",
    text: "A complete reliability system requires more than fixing failures. It requires predicting, preventing, assisting, and recovering.",
    duration: 4000,
  },
  ...SYSTEM_LAYERS.map((l) => ({
    id: l.id,
    text: `${l.action} · ${l.system}. ${l.body}`,
    duration: 4000,
  })),
  {
    id: "loop",
    text: "Together, these systems form a closed-loop reliability model.",
    duration: 4500,
  },
];
